### PR TITLE
Upgrade lodash from 3.x to 4.x

### PR DESCRIPTION
**Pull request by imjoshdean**

### CODE REVIEW

**Comment by mjstahl** [comment]
👍

**Comment by crookedneighbor** [comment]
Thanks for this PR, but one of our products that uses this module still supports IE8 (which lodash@4 no longer does), so we cannot merge this in right now. When we're ready to make a major version bump for this module, we'll revisit upgrading lodash (or remove the dependency entirely).

**Comment by imjoshdean** [comment]
Alright I understand. I will either need to fork the project or find a different solution. Best of luck!

**Comment by crookedneighbor** [comment]
:+1: I meant to suggest forking if you needed it to be on lodash@4.

**Pull request closed without merging**
